apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
      id: "0"
  template:
    metadata:
      labels:
        app: kafka-monitor
        id: "0"
    spec:
      containers:
        - name: kafka-monitor
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: 'api-kafka.default.svc.cluster.local:9092'

            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"

            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"

---
apiVersion: v1
kind: Service
metadata:
  name: api-kafka-monitor
  namespace: default
  labels:
    name: kafka-monitor
spec:
  ports:
    - port: 9000
      name: kafka-monitor-port
      protocol: TCP
  selector:
    app: kafka-monitor
    id: "0"

  type: NodePort
