apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-allocation-engine
spec:
  hosts:
    - api-allocation-engine
  http:
    - route:
      - destination:
          host: api-allocation-engine.default.svc.cluster.local
      retries:
        attempts: 4
        perTryTimeout: 2.5s