apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-allocation-engine
  labels:
    app: api-allocation-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-allocation-engine
  template:
    metadata:
      labels:
        app: api-allocation-engine
    spec:
      containers:
        - name: api-allocation-engine
          image: api-allocation-engine
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: password

            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://api-database:5432/api-footyandsweep?stringtype=unspecified'

            - name: KAFKA_CONNECT
              value: 'api-kafka.default.svc.cluster.local:9092'

            - name: ZOOKEEPER_CONNECT
              value: 'zookeeper:2181'

            - name: REDIS_CONNECT
              value: "api-redis-cache"

---
apiVersion: v1
kind: Service
metadata:
  name: api-allocation-engine
  labels:
    app: api-allocation-engine
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: api-allocation-engine
  type: NodePort