apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: api-result-engine
      docker:
        dockerfile: Dockerfile
  local: { }
deploy:
  kubectl:
    manifests:
      - ../kubernetes/api-result-engine/api-result-engine.yaml
