apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-result-engine
  namespace: default
spec:
  host: api-result-engine.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        maxRequestsPerConnection: 10
        http1MaxPendingRequests: 1024
    outlierDetection:
      consecutiveErrors: 7
      interval: 5m
      baseEjectionTime: 15m