apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-result-engine
  namespace: default
spec:
  gateways:
    - internal-gtw
    - mesh
  hosts:
    - "api.footyandsweep-dev.com"
  http:
    - match:
        - uri:
            prefix: /grpc
      route:
        - destination:
            host: api-result-engine.default.svc.cluster.local
            port:
              number: 9090

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: api-result-engine.default.svc.cluster.local
            port:
              number: 8080