apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-kafka
  namespace: default
spec:
  gateways:
    - internal-gtw
    - mesh
  hosts:
    - "api.footyandsweep-dev.com"
  tcp:
    - route:
      - destination:
          host: api-kafka.default.svc.cluster.local
          port:
            number: 9092