apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: footyandsweep-v2
build:
  artifacts:
  - image: api-gateway-service
    context: api-gateway-service
    docker: {}

  - image: api-sweepstake-engine
    context: api-sweepstake-engine
    docker: { }
deploy:
  kubectl:
    manifests:
    - kubernetes/api-database-storage.yaml
    - kubernetes/api-database.yaml
    - kubernetes/cluster-bindings.yaml
    - kubernetes/api-event-cdc/api-event-cdc.yaml
    - kubernetes/api-event-cdc/api-kafka.yaml
    - kubernetes/api-event-cdc/zookeeper.yaml
    - kubernetes/api-gateway-service/api-gateway-service-config.yaml
    - kubernetes/api-gateway-service/api-gateway-service-secrets.yaml
    - kubernetes/api-gateway-service/api-gateway-service.yaml
    - kubernetes/api-sweepstake-engine/api-sweepstake-engine-config.yaml
    - kubernetes/api-sweepstake-engine/api-sweepstake-engine-secrets.yaml
    - kubernetes/api-sweepstake-engine/api-sweepstake-engine.yaml
