apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: footyandsweep-v2
build:
  artifacts:
    - image: api-authentication-service
      context: api-authentication-service
      docker: { }
    - image: api-sweepstake-engine
      context: api-sweepstake-engine
      docker: { }
    - image: api-ticket-engine
      context: api-ticket-engine
      docker: { }
    - image: api-result-engine
      context: api-result-engine
      docker: { }
    - image: api-allocation-engine
      context: api-allocation-engine
      docker: { }
    - image: api-gateway-proxy
      context: kubernetes/api-gateway-proxy
      docker: { }
    - image: api-frontend-proxy
      context: kubernetes/api-frontend-proxy
      docker: { }
deploy:
  kubectl:
    manifests:
      - kubernetes/cluster-bindings.yaml
      - kubernetes/api-redis-cache/api-redis-cache.yaml
      - kubernetes/api-event-broker/api-kafka.yaml
      - kubernetes/api-event-broker/api-kafka-monitor.yaml
      - kubernetes/api-event-broker/zookeeper.yaml
      - kubernetes/api-frontend-proxy/api-frontend-proxy.yaml
      - kubernetes/api-authentication-service/api-authentication-service-config.yaml
      - kubernetes/api-sweepstake-engine/api-sweepstake-engine-config.yaml
      - kubernetes/api-ticket-engine/api-ticket-engine-config.yaml
      - kubernetes/api-result-engine/api-result-engine-config.yaml
      - kubernetes/api-allocation-engine/api-allocation-engine-config.yaml
      - kubernetes/api-sweepstake-engine/api-sweepstake-engine.yaml
      - kubernetes/api-ticket-engine/api-ticket-engine.yaml
      - kubernetes/api-result-engine/api-result-engine.yaml
      - kubernetes/api-allocation-engine/api-allocation-engine.yaml
      - kubernetes/api-authentication-service/api-authentication-service.yaml
      - kubernetes/api-gateway-proxy/api-gateway-proxy.yaml
      - kubernetes/api-event-broker/api-cdc-service.yaml
