apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-sweepstake-engine
  namespace: default
spec:
  gateways:
    - internal-gtw
    - mesh
  hosts:
    - api-sweepstake-engine.default.svc.cluster.local
  tcp:
  - route:
    - destination:
        host: api-sweepstake-engine.default.svc.cluster.local
        port:
          number: 8080
  http:
  - route:
      - destination:
          host: api-sweepstake-engine.default.svc.cluster.local
          port:
            number: 9090