apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  application.yml: |-
    spring:
      application:
        name: 'api-sweepstake-engine'

      jpa:
        generate-ddl: true

        show-sql: true

        properties:
          hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect

        hibernate:
          default_batch_fetch_size: 16

      datasource:
        driver-class-name: org.postgresql.Driver

    eventuate:
      redis:
        servers: 'api-event-cdc:6379'
        partitions: 2