apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-authentication-service
  labels:
    app: api-authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-authentication-service
  template:
    metadata:
      labels:
        app: api-authentication-service
    spec:
      containers:
        - name: api-authentication-service
          image: api-authentication-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: password

            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://api-database:5432/api-footyandsweep?stringtype=unspecified'

            - name: KAFKA_CONNECT
              value: 'api-kafka.default.svc.cluster.local:9092'

            - name: ZOOKEEPER_CONNECT
              value: 'zookeeper:2181'

            - name: REDIS_CONNECT
              value: "api-redis-cache"

---
apiVersion: v1
kind: Service
metadata:
  name: api-authentication-service
  labels:
    app: api-authentication-service
spec:
  ports:
    - port: 8080
      name: tcp
      targetPort: 8080
      nodePort: 30389
    - port: 9090
      name: http2
      protocol: TCP
      targetPort: 9090
  selector:
    app: api-authentication-service
  type: NodePort
