apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: api-gateway-service
      docker:
        dockerfile: Dockerfile
  local: { }
deploy:
  kubectl:
    manifests:
      - ../kubernetes/api-gateway-service/api-gateway-service.yaml
