apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: api-sweepstake-engine
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - ../kubernetes/api-sweepstake-engine/api-sweepstake-engine.yaml
