apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway-service
  namespace: default
spec:
  gateways:
    - mesh
    - internal-ingressgateway.istio-system.svc.cluster.local
  hosts:
    - api-gateway-service.default.svc.cluster.local
  http:
    - match:
        - port: 9090
        - uri:
            prefix: /grpc
      route:
        - destination:
            host: api-gateway-service.default.svc.cluster.local
            port:
              number: 9090

    - match:
        - port: 8080
        - uri:
            prefix: /
      route:
        - destination:
            host: api-gateway-service.default.svc.cluster.local
            port:
              number: 8080