apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway-service
  namespace: default
spec:
  gateways:
    - internal-gtw
  hosts:
    - "api.footyandsweep-dev.com"
  tcp:
    - route:
      - destination:
          host: api-gateway-service.default.svc.cluster.local
          port:
            number: 8080
  http:
    - match:
        - uri:
            prefix: /
      route:
      - destination:
          host: api-gateway-service.default.svc.cluster.local
          port:
            number: 9090