apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: ui-service
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - ../kubernetes/ui-service/ui-service.yaml
