POST http://localhost:8082/internal/sweepstake/save
Content-Type: application/json

{
  "name": "A Sweepstake",
  "isPrivate": true,
  "ownerId": "d913ed9d-ebfa-406d-bef1-8ee91a9ccda3",
  "numberOfRange": 5,
  "numberOfMax": 5,
  "maxNumberOfRanges": 5,
  "correctScoreMax": 7,
  "minuteRange": 5,
  "includeBench": false,
  "includeStartingGoalkeeper": false,
  "includeNoGoalScorer": false,
  "includeOwnGoals": true,
  "stake": 1.00
}

###

POST http://localhost:8082/internal/ticket/buy
Content-Type: application/json

{
  "ownerId": "d913ed9d-ebfa-406d-bef1-8ee91a9ccda3",
  "joinCode": "SXpn34jE",
  "numberOfTickets": 3
}

###

