POST http://localhost:8082/internal/sweepstake/save
Content-Type: application/json

{
  "name": "Ben's Sweepstake",
  "isPrivate": true,
  "ownerId": "123e4567-e89b-42d3-a456-556642440000",
  "numberOfRange": 5,
  "numberOfMax": 5,
  "maxNumberOfRanges": 5,
  "correctScoreMax": 7,
  "minuteRange": 5,
  "includeBench": false,
  "includeStartingGoalkeeper": false,
  "includeNoGoalScorer": false,
  "includeOwnGoals": true,
  "stake": 100.00
}

###

POST http://localhost:8082/internal/ticket/buy
Content-Type: application/json

{
  "ownerId": "123e4567-e89b-42d3-a456-556642440000",
  "joinCode": "t2vF1JTX",
  "numberOfTickets": 1
}

###

