POST http://localhost:8081/internal/sweepstake/save
Content-Type: application/json

{
  "name": "Ben's Sweepstake",
  "isPrivate": true,
  "ownerId": "f76a74ae-83b6-389c-82ca-8ac0b9febd33",
  "numberOfRange": 5,
  "numberOfMax": 5,
  "maxNumberOfRanges": 5,
  "correctScoreMax": 7,
  "minuteRange": 5,
  "includeBench": false,
  "includeStartingGoalkeeper": false,
  "includeNoGoalScorer": false,
  "includeOwnGoals": true,
  "stake": 100.00
}

###

POST http://localhost:8081/internal/ticket/buy
Content-Type: application/json

{
  "ownerId": "f76a74ae-83b6-389c-82ca-8ac0b9febd33",
  "joinCode": "xWwAvg9M",
  "numberOfTickets": 1
}

###
