POST http://localhost:8081/internal/sweepstake/save
Content-Type: application/json

{
  "name": "Sweepstake name",
  "isPrivate": true,
  "ownerId": "045a5642-68a0-4d14-b19c-29e51ec9c9ee",
  "numberOfRange": 5,
  "numberOfMax": 5,
  "maxNumberOfRanges": 5,
  "correctScoreMax": 7,
  "minuteRange": 5,
  "includeBench": false,
  "includeStartingGoalkeeper": false,
  "includeNoGoalScorer": false,
  "includeOwnGoals": true,
  "stake": 100.00
}

###

