apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-result-engine
  labels:
    app: api-result-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-result-engine
  template:
    metadata:
      labels:
        app: api-result-engine
    spec:
      containers:
        - name: api-result-engine
          image: api-result-engine
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-result-engine-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-result-engine-credentials
                  key: password

            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://api-database:5432/api-footyandsweep?stringtype=unspecified'

            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: 'api-kafka.default.svc.cluster.local:9092'

            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: 'zookeeper:2181'

---
apiVersion: v1
kind: Service
metadata:
  name: api-result-engine
  labels:
    app: api-result-engine
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: api-result-engine
  type: NodePort