apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-ticket-engine
  namespace: default
spec:
  gateways:
    - internal-gtw
  hosts:
    - "*"
  tcp:
  - route:
    - destination:
        host: api-ticket-engine.default.svc.cluster.local
        port:
          number: 8080
  http:
  - route:
    - destination:
        host: api-ticket-engine.default.svc.cluster.local
        port:
          number: 9090