apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: api-gateway-proxy
      docker:
        dockerfile: Dockerfile
  local: { }

deploy:
  kubectl:
    manifests:
      - './api-gateway-proxy.yaml'