apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      id: "0"
  template:
    metadata:
      labels:
        app: redis
        id: "0"
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: api-redis-cache
  namespace: default
  labels:
    name: redis
spec:
  ports:
    - port: 6379
      name: redis-port
      protocol: TCP
  selector:
    app: redis
    id: "0"

  type: NodePort
