apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: api-frontend-proxy
      docker:
        dockerfile: Dockerfile
  local: { }
deploy:
  kubectl:
    manifests:
      - ./api-frontend-proxy.yaml
