apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-events-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-events-redis
  template:
    metadata:
      labels:
        app: api-events-redis
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: redis
          image: redis:5.0.7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: api-events-redis
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    app: api-events-redis