apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-events-cdc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-events-cdc
  template:
    metadata:
      labels:
        app: api-events-cdc
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: cdc-service
          image: eventuateio/eventuate-cdc-service:0.6.1.RELEASE
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sweepstake-engine-credentials
                  key: password

            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://api-sweepstake-engine-db:5432/api-sweepstake-engine'

            - name: EVENTUATELOCAL_CDC_DB_USER_NAME
              value: 'root'

            - name: EVENTUATELOCAL_CDC_DB_PASSWORD
              value: 'rootpassword'

            - name: SPRING_DATASOURCE_VALIDATION_QUERY
              value: 'SELECT 1'

            - name: EVENTUATE_REDIS_SERVERS
              value: api-event-redis:6379

            - name: EVENTUATE_REDIS_PARTITIONS
              value: "2"

            - name: JAVA_OPTS
              value: '-Xmx128m'

            - name: EVENTUATELOCAL_CDC_READER_NAME
              value: 'ClientEventuateTram'
---
apiVersion: v1
kind: Service
metadata:
  name: api-events-cdc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: api-events-cdc