apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 30035
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: KAFKA_ADVERTISED_PORT
              value: "9092"

            - name: KAFKA_HEAP_OPTS
              value: -Xms320m

            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"

---
apiVersion: v1
kind: Service
metadata:
  name: api-kafka
  namespace: default
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"

  type: NodePort
