spring:
  application:
    name: 'api-sweepstake-engine'

  kafka:
    bootstrap-servers: ${KAFKA_CONNECT}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: api-event
      enable-auto-commit: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    acks: all
    retries: 5
    retry:
      backoff:
        ms: 5000

  jpa:
    generate-ddl: true

    show-sql: false

    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      default_batch_fetch_size: 16

    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

  redis:
    host: "api-redis-cache"
    port: 6379

  cache:
    type: redis
