spring:
  application:
    name: 'api-sweepstake-engine'

  sleuth:
    enabled: true
    sampler:
      probability: 1

  zipkin:
    base:
      url: http://${ZIPKIN_CONNECT}

  jpa:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_CONNECT}
    port: 6379

  cache:
    type: redis

grpc:
  server:
    port: 9090

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_CONNECT}

  zookeeper:
    connection:
      string: ${ZOOKEEPER_CONNECT}