kind: PersistentVolume
apiVersion: v1
metadata:
  name: api-database-volume
  labels:
    type: local
    app: api-database
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-database-claim
  labels:
    app: api-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi