apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-gtw
  namespace: default
  labels:
    app: internal-gtw
spec:
  selector:
    istio: ingressgateway
    app: internal-ingressgateway
  servers:
    - port:
        number: 443
        protocol: HTTPS
        name: https
      tls:
        mode: SIMPLE
        credentialName: footyandsweep-dev-credential
      hosts:
        - "api.footyandsweep-dev.com"