apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-ingressgateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
    app: internal-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      tls:
        httpsRedirect: true
    - port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: footyandsweep-dev-credential
      hosts:
        - "*"