spring:
  application:
    name: 'api-ticket-engine'

  kafka:
    bootstrap-servers: ${KAFKA_CONNECT}
    consumer:
      auto-offset-reset: earliest
      group-id: api-event
      enable-auto-commit: true

    acks: all
    retries: 5
    retry:
      backoff:
        ms: 5000

  jpa:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_CONNECT}
    port: 6379

  cache:
    type: redis

