spring:
  application:
    name: 'api-gateway-service'

  sleuth:
    enabled: true
    sampler:
      probability: 1

  zipkin:
    base:
      url: https://${ZIPKIN_CONNECT}

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cloud:
    gateway:
      enabled: true

      routes:
        - id: 'api-sweepstake-engine'
          uri: 'ws://api-sweepstake-engine.default.svc.cluster.local:8080'
          predicates:
            - Path=/sweepstake-socket/**
          filters:
            - StripPrefix=1

        - id: 'api-sweepstake-engine'
          uri: 'http://api-sweepstake-engine:8080'
          predicates:
            - Path=/sweepstake/**
          filters:
            - StripPrefix=1

        - id: 'api-ticket-engine'
          uri: 'ws://api-ticket-engine:8080'
          predicates:
            - Path=/ticket-socket/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 741479066693-5r73putvt12rf6flqphppn6181hu9ldg.apps.googleusercontent.com
            clientSecret: HzucWNSw6jgqcwp1EiJL6Omn
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

          facebook:
            clientId: 695015954517496
            clientSecret: 8a20fbf69495879823be75828d0f2ab4
            scope:
              - email
              - public_profile

        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)


  main:
    allow-bean-definition-overriding: true

footyandsweep:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000000

  oauth2:
    authorizedRedirectUris:
      - https://www.footyandsweep-dev.com:3000/oauth2/redirect

grpc:
  server:
    port: 9090

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_CONNECT}

  zookeeper:
    connection:
      string: ${ZOOKEEPER_CONNECT}

server:
  port: 8080

  error:
    whitelabel:
      enabled: false

  servlet:
    session:
      persistent: false
      timeout: 0