spring:
  application:
    name: 'api-gateway-service'

  cloud:
    gateway:
      routes:
        - id: 'api-sweepstake-engine'
          uri: 'ws://api-sweepstake-engine:8080'
          predicates:
            - Path=/sweepstake/**
          filters:
            - StripPrefix=1

server:
  port: 8080