spring:
  application:
    name: 'api-gateway-service'

  cloud:
    gateway:
      routes:
#        - id: 'api-sweepstake-engine-http'
#          uri: 'http://api-sweepstake-engine:8080'
#          predicates:
#            - Path=/sweepstake/**
#          filters:
#            - StripPrefix=1
#            - GatewayFilter

        - id: 'api-sweepstake-engine-websocket'
          uri: 'ws://api-sweepstake-engine:8080'
          predicates:
            - Path=/sweepstake/socket/**
          filters:
            - StripPrefix=1
            - GatewayFilter

        - id: 'api-authentication-service'
          uri: 'http://api-authentication-service:8080'
          predicates:
            - Path=/oauth2/**
          filters:
            - StripPrefix=0

  main:
    allow-bean-definition-overriding: true

footyandsweep:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000000

  oauth2:
    authorizedRedirectUris:
      - https://www.footyandsweep-dev.com:3000/oauth2/redirect

server:
  port: 8080
