spring:
  application:
    name: 'api-gateway-service'

  jpa:
    generate-ddl: true

    show-sql: true

    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      default_batch_fetch_size: 16

  datasource:
    url: 'jdbc:postgresql://192.168.1.135:30526/api-footyandsweep'
    username: '1fca2772-4c82-4653-a8eb-291db6f25679'
    password: 'c7a25b8c-1dfb-4da3-a6f1-baee0afc21a6'
    driver-class-name: org.postgresql.Driver

eventuate:
  redis:
    servers: 192.168.1.135:31294
    partitions: 2

  database:
    schema: eventuate


zuul:
  routes:
    api-sweepstake-engine:
      path: '/internal/sweepstake/**'
      serviceId: 'api-sweepstake-engine'
      url: 'http://192.168.1.135:30959/'
      sensitiveHeaders:
      stripPrefix: false